# Generated by Django 3.2.5 on 2021-08-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=200)),
                ('job', models.CharField(max_length=100)),
                ('employed_year', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField()),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='post/')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employ_type', models.CharField(choices=[('인턴', '인턴'), ('정규', '정규'), ('IPP', 'IPP')], max_length=20)),
                ('job_type', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=20)),
                ('school_number', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
