# Generated by Django 3.2.5 on 2021-08-17 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=200)),
                ('job', models.CharField(max_length=100)),
                ('employed_year', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField()),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='post/')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employ_type', models.CharField(choices=[('인턴', '인턴'), ('IPP', 'IPP'), ('정규', '정규')], max_length=20)),
                ('job_type', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=20)),
                ('school_number', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField()),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
