# Generated by Django 3.2.5 on 2021-07-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employ_type', models.CharField(choices=[('정규', '정규'), ('IPP', 'IPP'), ('인턴', '인턴')], max_length=20)),
                ('job_type', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=20)),
                ('school_number', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('private', models.BooleanField()),
            ],
        ),
    ]
