# Generated by Django 3.2.5 on 2021-09-11 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_request_employ_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='employ_type',
            field=models.CharField(choices=[('IPP', 'IPP'), ('정규', '정규'), ('인턴', '인턴')], max_length=20),
        ),
    ]
