# Generated by Django 3.2.5 on 2021-09-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210906_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='employ_type',
            field=models.CharField(choices=[('인턴', '인턴'), ('IPP', 'IPP'), ('정규', '정규')], max_length=20),
        ),
    ]
